title: "Cards"
description: |
  This will hold cards and photos of the items of the items, all will be the same size

patterns:
  product-card:
    title: "Products"
    description: |
        This will be a card for items on the site, all the same size.
    width: "24em"

  product-info:
    title: "Product Info"
    description: |
        This is the card will all the specific info on the item, once it is selected and a button to buy it.
    width: "36em"
    background: "--color-light-grey"

    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
