title: "Navigation"
description: |
  This will be the main navigation at top of page

patterns:
  nav:
    title: "Main navigation"
    description: |
        This will be the main navigation for the top of the site, this will appear on every page.
