title: "Secondary Navigation"
description: |
  This will be the secondary navigation for the products, it will be on photos of products to show different angles and uses.

patterns:
  carousel:
    title: "Carousel"
    description: |
        This will be on the product picture, pictures will change as requested.
