title: "carousel"
description: |
  This will be the secondary navigation for the products.

patterns:
  secondary-nav:
    title: "secondary navigation"
    description: |
        This will be on the product picture, pictures will change as requested.
