title: "Secondary Navigation"
description: |
  This will be the secondary navigation for the products.

patterns:
  carousel:
    title: "Carousel"
    description: |
        This will be on the product picture, pictures will change as requested.
